<?php

namespace ProductBundle\Repository;

/**
 * ArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtRepository extends \Doctrine\ORM\EntityRepository
{
}
